# .woodpecker.yml
pipeline:
  build:
    image: docker:20.10.16
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_CLI_EXPERIMENTAL=enabled
      - CONCRETE_CMS_REPO_URL: "https://github.com/concrete5/concrete5.git"
      - IMAGE_NAME: gijsen/concrete-cms
      - TAG: latest

    steps:
      # Step 1: Clone the Concrete CMS repo
      - name: Checkout Concrete CMS
        image: alpine:3.14
        commands:
          - git clone ${CONCRETE_CMS_REPO_URL} concrete5

      # Step 2: Build the Docker image
      - name: Build Concrete CMS Docker image
        image: docker:20.10.16
        commands:
          - cd concrete5
          - docker build -t ${IMAGE_NAME}:${TAG} .

      # Step 3: Push the image to the Docker registry
      - name: Push Docker image to registry
        image: docker:20.10.16
        commands:
          - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          - docker push ${IMAGE_NAME}:${TAG}
